name = "kitchensoftware"
type = "javascript"

[build]
command = "npm run build"

# Specify the main entry point to your Worker script
main = "src/index.js"  # Or the correct path to your Worker script

[[d1_databases]]
binding = "DB"
database_name = "kitchen-db"
database_id = "068dbf37-8e1d-4ca9-8617-199fb26450b7"
