name = "kitchensoftware"
type = "javascript"

[build]
command = "npm run build"
cwd = "."  # Optional: Make sure the working directory is set correctly if needed

# Specify the output file or folder from the build process if necessary
# This might be 'dist/index.js' or another path depending on your build setup
main = "dist/index.js"  # Ensure this is where your build output is

workers_dev = true  # Optional: Enable if running locally for development

[[d1_databases]]
binding = "DB"
database_name = "kitchen-db"
database_id = "068dbf37-8e1d-4ca9-8617-199fb26450b7"
